// Code generated by protoc-gen-go. DO NOT EDIT.
// source: edge.proto

package cds_cabinet_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Edge struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Predicate            uint32   `protobuf:"varint,2,opt,name=predicate,proto3" json:"predicate,omitempty"`
	Target               string   `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Properties           []byte   `protobuf:"bytes,10,opt,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Edge) Reset()         { *m = Edge{} }
func (m *Edge) String() string { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()    {}
func (*Edge) Descriptor() ([]byte, []int) {
	return fileDescriptor_cab1176173a95651, []int{0}
}

func (m *Edge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Edge.Unmarshal(m, b)
}
func (m *Edge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Edge.Marshal(b, m, deterministic)
}
func (m *Edge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Edge.Merge(m, src)
}
func (m *Edge) XXX_Size() int {
	return xxx_messageInfo_Edge.Size(m)
}
func (m *Edge) XXX_DiscardUnknown() {
	xxx_messageInfo_Edge.DiscardUnknown(m)
}

var xxx_messageInfo_Edge proto.InternalMessageInfo

func (m *Edge) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Edge) GetPredicate() uint32 {
	if m != nil {
		return m.Predicate
	}
	return 0
}

func (m *Edge) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Edge) GetProperties() []byte {
	if m != nil {
		return m.Properties
	}
	return nil
}

func init() {
	proto.RegisterType((*Edge)(nil), "cds.cabinet.v1.Edge")
}

func init() { proto.RegisterFile("edge.proto", fileDescriptor_cab1176173a95651) }

var fileDescriptor_cab1176173a95651 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4d, 0x49, 0x4f,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4b, 0x4e, 0x29, 0xd6, 0x4b, 0x4e, 0x4c, 0xca,
	0xcc, 0x4b, 0x2d, 0xd1, 0x2b, 0x33, 0x54, 0x2a, 0xe3, 0x62, 0x71, 0x4d, 0x49, 0x4f, 0x15, 0x92,
	0xe0, 0x62, 0x2f, 0x2e, 0x4d, 0xca, 0x4a, 0x4d, 0x2e, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x82, 0x71, 0x85, 0x64, 0xb8, 0x38, 0x0b, 0x8a, 0x52, 0x53, 0x32, 0x93, 0x13, 0x4b, 0x52, 0x25,
	0x98, 0x14, 0x18, 0x35, 0x78, 0x83, 0x10, 0x02, 0x42, 0x62, 0x5c, 0x6c, 0x25, 0x89, 0x45, 0xe9,
	0xa9, 0x25, 0x12, 0xcc, 0x60, 0x6d, 0x50, 0x9e, 0x90, 0x1c, 0x17, 0x57, 0x41, 0x51, 0x7e, 0x41,
	0x6a, 0x51, 0x49, 0x66, 0x6a, 0xb1, 0x04, 0x97, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x92, 0x48, 0x12,
	0x1b, 0xd8, 0x39, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xed, 0x82, 0x1a, 0x6e, 0x9c, 0x00,
	0x00, 0x00,
}
