// Code generated by protoc-gen-go. DO NOT EDIT.
// source: index.proto

package cds_cabinet_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Index struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Node                 string   `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Properties           []byte   `protobuf:"bytes,10,opt,name=properties,proto3" json:"properties,omitempty"`
	Unique               bool     `protobuf:"varint,11,opt,name=unique,proto3" json:"unique,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{0}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Index) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *Index) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Index) GetProperties() []byte {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Index) GetUnique() bool {
	if m != nil {
		return m.Unique
	}
	return false
}

type IndexChoice struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexChoice) Reset()         { *m = IndexChoice{} }
func (m *IndexChoice) String() string { return proto.CompactTextString(m) }
func (*IndexChoice) ProtoMessage()    {}
func (*IndexChoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{1}
}

func (m *IndexChoice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexChoice.Unmarshal(m, b)
}
func (m *IndexChoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexChoice.Marshal(b, m, deterministic)
}
func (m *IndexChoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexChoice.Merge(m, src)
}
func (m *IndexChoice) XXX_Size() int {
	return xxx_messageInfo_IndexChoice.Size(m)
}
func (m *IndexChoice) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexChoice.DiscardUnknown(m)
}

var xxx_messageInfo_IndexChoice proto.InternalMessageInfo

func (m *IndexChoice) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *IndexChoice) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*Index)(nil), "cds.cabinet.v1.Index")
	proto.RegisterType((*IndexChoice)(nil), "cds.cabinet.v1.IndexChoice")
}

func init() { proto.RegisterFile("index.proto", fileDescriptor_f750e0f7889345b5) }

var fileDescriptor_f750e0f7889345b5 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x86, 0x89, 0xb6, 0x45, 0xaf, 0xea, 0x10, 0x8a, 0x64, 0x92, 0xd0, 0x29, 0x53, 0x41, 0x9c,
	0x9c, 0x9d, 0x5c, 0xf3, 0x06, 0x6d, 0x7a, 0x60, 0x40, 0x92, 0xd8, 0x26, 0x45, 0x07, 0xdf, 0x5d,
	0x9a, 0x3a, 0x64, 0xfb, 0xbf, 0xef, 0xe0, 0xbf, 0x3b, 0x28, 0xb5, 0xe9, 0xf1, 0xdd, 0xb8, 0xc1,
	0x7a, 0x4b, 0x0f, 0xaa, 0x1f, 0x1b, 0xd5, 0x76, 0xda, 0xa0, 0x6f, 0xa6, 0x73, 0xfd, 0x85, 0xfc,
	0x3e, 0x8f, 0x29, 0x85, 0xcc, 0x7f, 0x1c, 0x32, 0xc2, 0x89, 0xd8, 0xcb, 0x98, 0x67, 0x67, 0x6c,
	0x8f, 0x6c, 0xcd, 0x89, 0xd8, 0xca, 0x98, 0x69, 0x05, 0xf9, 0xd4, 0x3e, 0x03, 0xb2, 0x2c, 0xca,
	0x05, 0xe8, 0x09, 0xc0, 0x0d, 0xd6, 0xe1, 0xe0, 0x35, 0x8e, 0x0c, 0x38, 0x11, 0x3b, 0x99, 0x18,
	0x7a, 0x84, 0x22, 0x18, 0xfd, 0x0a, 0xc8, 0x4a, 0x4e, 0xc4, 0x46, 0xfe, 0xa9, 0xbe, 0x42, 0x19,
	0xd7, 0xdf, 0x1e, 0x56, 0xab, 0xa4, 0x9c, 0xa4, 0xe5, 0x15, 0xe4, 0xca, 0x06, 0xe3, 0xd9, 0x2a,
	0xde, 0xb6, 0x40, 0x57, 0xc4, 0x87, 0x2e, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x08, 0xff, 0xe1,
	0xb2, 0xdf, 0x00, 0x00, 0x00,
}
