// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sequential.proto

package cds_cabinet_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Sequential struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Seqid                uint32   `protobuf:"varint,2,opt,name=seqid,proto3" json:"seqid,omitempty"`
	Uuid                 string   `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sequential) Reset()         { *m = Sequential{} }
func (m *Sequential) String() string { return proto.CompactTextString(m) }
func (*Sequential) ProtoMessage()    {}
func (*Sequential) Descriptor() ([]byte, []int) {
	return fileDescriptor_c98343d0a957163b, []int{0}
}

func (m *Sequential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sequential.Unmarshal(m, b)
}
func (m *Sequential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sequential.Marshal(b, m, deterministic)
}
func (m *Sequential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sequential.Merge(m, src)
}
func (m *Sequential) XXX_Size() int {
	return xxx_messageInfo_Sequential.Size(m)
}
func (m *Sequential) XXX_DiscardUnknown() {
	xxx_messageInfo_Sequential.DiscardUnknown(m)
}

var xxx_messageInfo_Sequential proto.InternalMessageInfo

func (m *Sequential) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Sequential) GetSeqid() uint32 {
	if m != nil {
		return m.Seqid
	}
	return 0
}

func (m *Sequential) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*Sequential)(nil), "cds.cabinet.v1.Sequential")
}

func init() { proto.RegisterFile("sequential.proto", fileDescriptor_c98343d0a957163b) }

var fileDescriptor_c98343d0a957163b = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x4e, 0x2d, 0x2c,
	0x4d, 0xcd, 0x2b, 0xc9, 0x4c, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4b, 0x4e,
	0x29, 0xd6, 0x4b, 0x4e, 0x4c, 0xca, 0xcc, 0x4b, 0x2d, 0xd1, 0x2b, 0x33, 0x54, 0xf2, 0xe2, 0xe2,
	0x0a, 0x86, 0xab, 0x11, 0x12, 0xe2, 0x62, 0x29, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x44, 0xb8, 0x58, 0x8b, 0x53, 0x0b, 0x33, 0x53, 0x24, 0x98, 0x14,
	0x18, 0x35, 0x78, 0x83, 0x20, 0x1c, 0x90, 0xca, 0xd2, 0xd2, 0xcc, 0x14, 0x09, 0x16, 0x88, 0x4a,
	0x10, 0x3b, 0x89, 0x0d, 0x6c, 0x85, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x14, 0x71, 0xed, 0xd5,
	0x76, 0x00, 0x00, 0x00,
}
