// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_meta.proto

package cds_cabinet_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MetaGetResponse struct {
	Val                  []byte   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaGetResponse) Reset()         { *m = MetaGetResponse{} }
func (m *MetaGetResponse) String() string { return proto.CompactTextString(m) }
func (*MetaGetResponse) ProtoMessage()    {}
func (*MetaGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9788f851de37978a, []int{0}
}

func (m *MetaGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaGetResponse.Unmarshal(m, b)
}
func (m *MetaGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaGetResponse.Marshal(b, m, deterministic)
}
func (m *MetaGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaGetResponse.Merge(m, src)
}
func (m *MetaGetResponse) XXX_Size() int {
	return xxx_messageInfo_MetaGetResponse.Size(m)
}
func (m *MetaGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetaGetResponse proto.InternalMessageInfo

func (m *MetaGetResponse) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

type MetaListRequest struct {
	Opt                  *ListOptions `protobuf:"bytes,1,opt,name=opt,proto3" json:"opt,omitempty"`
	Meta                 *Meta        `protobuf:"bytes,10,opt,name=meta,proto3" json:"meta,omitempty"`
	IncludeNode          bool         `protobuf:"varint,20,opt,name=include_node,json=includeNode,proto3" json:"include_node,omitempty"`
	IncludeProperty      bool         `protobuf:"varint,21,opt,name=include_property,json=includeProperty,proto3" json:"include_property,omitempty"`
	IncludeValue         bool         `protobuf:"varint,22,opt,name=include_value,json=includeValue,proto3" json:"include_value,omitempty"`
	IncludeSubject       bool         `protobuf:"varint,23,opt,name=include_subject,json=includeSubject,proto3" json:"include_subject,omitempty"`
	IncludePredicate     bool         `protobuf:"varint,24,opt,name=include_predicate,json=includePredicate,proto3" json:"include_predicate,omitempty"`
	IncludeTarget        bool         `protobuf:"varint,25,opt,name=include_target,json=includeTarget,proto3" json:"include_target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MetaListRequest) Reset()         { *m = MetaListRequest{} }
func (m *MetaListRequest) String() string { return proto.CompactTextString(m) }
func (*MetaListRequest) ProtoMessage()    {}
func (*MetaListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9788f851de37978a, []int{1}
}

func (m *MetaListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaListRequest.Unmarshal(m, b)
}
func (m *MetaListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaListRequest.Marshal(b, m, deterministic)
}
func (m *MetaListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaListRequest.Merge(m, src)
}
func (m *MetaListRequest) XXX_Size() int {
	return xxx_messageInfo_MetaListRequest.Size(m)
}
func (m *MetaListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetaListRequest proto.InternalMessageInfo

func (m *MetaListRequest) GetOpt() *ListOptions {
	if m != nil {
		return m.Opt
	}
	return nil
}

func (m *MetaListRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *MetaListRequest) GetIncludeNode() bool {
	if m != nil {
		return m.IncludeNode
	}
	return false
}

func (m *MetaListRequest) GetIncludeProperty() bool {
	if m != nil {
		return m.IncludeProperty
	}
	return false
}

func (m *MetaListRequest) GetIncludeValue() bool {
	if m != nil {
		return m.IncludeValue
	}
	return false
}

func (m *MetaListRequest) GetIncludeSubject() bool {
	if m != nil {
		return m.IncludeSubject
	}
	return false
}

func (m *MetaListRequest) GetIncludePredicate() bool {
	if m != nil {
		return m.IncludePredicate
	}
	return false
}

func (m *MetaListRequest) GetIncludeTarget() bool {
	if m != nil {
		return m.IncludeTarget
	}
	return false
}

func init() {
	proto.RegisterType((*MetaGetResponse)(nil), "cds.cabinet.v1.MetaGetResponse")
	proto.RegisterType((*MetaListRequest)(nil), "cds.cabinet.v1.MetaListRequest")
}

func init() { proto.RegisterFile("service_meta.proto", fileDescriptor_9788f851de37978a) }

var fileDescriptor_9788f851de37978a = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xd1, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc7, 0x71, 0xe6, 0x44, 0xe4, 0x6c, 0x6e, 0x33, 0x4c, 0x8d, 0xf3, 0x66, 0x6e, 0x88, 0x13,
	0xb1, 0xa0, 0x3e, 0x84, 0x37, 0xfe, 0xa3, 0x8a, 0xb7, 0x25, 0x4b, 0x0e, 0x1a, 0x99, 0x4d, 0x4c,
	0x4e, 0x0b, 0xbe, 0xaa, 0x4f, 0x23, 0x49, 0x1b, 0x87, 0xde, 0x95, 0x6f, 0x3f, 0xe9, 0xaf, 0x10,
	0x60, 0x1e, 0x5d, 0xad, 0x25, 0x16, 0x1f, 0x48, 0x22, 0xb3, 0xce, 0x90, 0x61, 0x03, 0xa9, 0x7c,
	0x26, 0xc5, 0x52, 0x97, 0x48, 0x59, 0x7d, 0x39, 0xe9, 0xfb, 0x37, 0xe1, 0x50, 0x35, 0x6f, 0x27,
	0xb0, 0x96, 0xb3, 0x39, 0x0c, 0xef, 0x90, 0xc4, 0x0d, 0x52, 0x8e, 0xde, 0x9a, 0xd2, 0x23, 0x1b,
	0x41, 0xb7, 0x16, 0x2b, 0xde, 0x99, 0x76, 0x16, 0xfd, 0x3c, 0x3c, 0xce, 0xbe, 0x37, 0x1a, 0x75,
	0xab, 0x3d, 0xe5, 0xf8, 0x59, 0xa1, 0x27, 0x76, 0x01, 0x5d, 0x63, 0x29, 0xaa, 0xde, 0xd5, 0x51,
	0xf6, 0x77, 0x30, 0x0b, 0xf2, 0xc1, 0x92, 0x36, 0xa5, 0xcf, 0x83, 0x63, 0x0b, 0xd8, 0x0c, 0xab,
	0x1c, 0xa2, 0x1f, 0xff, 0xf7, 0xe1, 0xeb, 0x79, 0x14, 0xec, 0x18, 0xfa, 0xba, 0x94, 0xab, 0x4a,
	0x61, 0x51, 0x1a, 0x85, 0x7c, 0x3c, 0xed, 0x2c, 0xb6, 0xf3, 0x5e, 0xdb, 0xee, 0x8d, 0x42, 0x76,
	0x06, 0xa3, 0x44, 0xac, 0x33, 0x16, 0x1d, 0x7d, 0xf1, 0xbd, 0xc8, 0x86, 0x6d, 0x7f, 0x6c, 0x33,
	0x9b, 0xc3, 0x4e, 0xa2, 0xb5, 0x58, 0x55, 0xc8, 0xf7, 0xa3, 0x4b, 0x13, 0x2f, 0xa1, 0xb1, 0x53,
	0x48, 0xe7, 0x0a, 0x5f, 0x2d, 0xdf, 0x51, 0x12, 0x3f, 0x88, 0x6c, 0xd0, 0xe6, 0xa7, 0xa6, 0xb2,
	0x73, 0xd8, 0x5d, 0x0f, 0xa3, 0xd2, 0x52, 0x10, 0x72, 0x1e, 0xe9, 0xe8, 0x77, 0xb9, 0xed, 0xec,
	0x04, 0xd2, 0xf1, 0x82, 0x84, 0x7b, 0x45, 0xe2, 0x87, 0x51, 0xa6, 0x1f, 0x7a, 0x8e, 0x71, 0xb9,
	0x15, 0x2f, 0xe2, 0xfa, 0x27, 0x00, 0x00, 0xff, 0xff, 0x66, 0xbc, 0x7f, 0x60, 0xc8, 0x01, 0x00,
	0x00,
}
