// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_sequential.proto

package cds_cabinet_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SequentialListRequest struct {
	Opt                  *ListOptions `protobuf:"bytes,1,opt,name=opt,proto3" json:"opt,omitempty"`
	Type                 string       `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	IncludeType          bool         `protobuf:"varint,20,opt,name=include_type,json=includeType,proto3" json:"include_type,omitempty"`
	IncludeSeqid         bool         `protobuf:"varint,21,opt,name=include_seqid,json=includeSeqid,proto3" json:"include_seqid,omitempty"`
	IncludeUuid          bool         `protobuf:"varint,22,opt,name=include_uuid,json=includeUuid,proto3" json:"include_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SequentialListRequest) Reset()         { *m = SequentialListRequest{} }
func (m *SequentialListRequest) String() string { return proto.CompactTextString(m) }
func (*SequentialListRequest) ProtoMessage()    {}
func (*SequentialListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de458bb8d17067b7, []int{0}
}

func (m *SequentialListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SequentialListRequest.Unmarshal(m, b)
}
func (m *SequentialListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SequentialListRequest.Marshal(b, m, deterministic)
}
func (m *SequentialListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SequentialListRequest.Merge(m, src)
}
func (m *SequentialListRequest) XXX_Size() int {
	return xxx_messageInfo_SequentialListRequest.Size(m)
}
func (m *SequentialListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SequentialListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SequentialListRequest proto.InternalMessageInfo

func (m *SequentialListRequest) GetOpt() *ListOptions {
	if m != nil {
		return m.Opt
	}
	return nil
}

func (m *SequentialListRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SequentialListRequest) GetIncludeType() bool {
	if m != nil {
		return m.IncludeType
	}
	return false
}

func (m *SequentialListRequest) GetIncludeSeqid() bool {
	if m != nil {
		return m.IncludeSeqid
	}
	return false
}

func (m *SequentialListRequest) GetIncludeUuid() bool {
	if m != nil {
		return m.IncludeUuid
	}
	return false
}

func init() {
	proto.RegisterType((*SequentialListRequest)(nil), "cds.cabinet.v1.SequentialListRequest")
}

func init() { proto.RegisterFile("service_sequential.proto", fileDescriptor_de458bb8d17067b7) }

var fileDescriptor_de458bb8d17067b7 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x09, 0x8a, 0x68, 0x76, 0xf5, 0x10, 0x5c, 0x09, 0x7a, 0xa9, 0x7a, 0xe9, 0xc5, 0x80,
	0xfa, 0x1a, 0x82, 0x90, 0xd5, 0xf3, 0xd2, 0x26, 0x03, 0x0e, 0x94, 0x24, 0xed, 0x4c, 0x0a, 0x3e,
	0xa0, 0xef, 0x25, 0x89, 0x56, 0xec, 0x2d, 0xf9, 0xff, 0xef, 0xff, 0x60, 0xa4, 0x26, 0x98, 0x66,
	0x74, 0x70, 0x20, 0x18, 0x33, 0x04, 0xc6, 0x6e, 0x30, 0x69, 0x8a, 0x1c, 0xd5, 0x85, 0xf3, 0x64,
	0x5c, 0xd7, 0x63, 0x00, 0x36, 0xf3, 0xe3, 0xf5, 0x96, 0x3e, 0xba, 0x09, 0xfc, 0x4f, 0x7b, 0xf7,
	0x25, 0xe4, 0x6e, 0xff, 0x37, 0x79, 0x41, 0x62, 0x5b, 0x7e, 0xc4, 0xea, 0x41, 0x1e, 0xc5, 0xc4,
	0x5a, 0x34, 0xa2, 0xdd, 0x3c, 0xdd, 0x98, 0xb5, 0xc5, 0x14, 0xf2, 0x35, 0x31, 0xc6, 0x40, 0xb6,
	0x70, 0x4a, 0xc9, 0x63, 0xfe, 0x4c, 0xa0, 0x65, 0x23, 0xda, 0x33, 0x5b, 0xdf, 0xea, 0x56, 0x6e,
	0x31, 0xb8, 0x21, 0x7b, 0x38, 0xd4, 0xee, 0xb2, 0x11, 0xed, 0xa9, 0xdd, 0xfc, 0x66, 0x6f, 0x05,
	0xb9, 0x97, 0xe7, 0x0b, 0x42, 0x30, 0xa2, 0xd7, 0xbb, 0xca, 0x2c, 0xbb, 0x7d, 0xc9, 0xfe, 0x7b,
	0x72, 0x46, 0xaf, 0xaf, 0x56, 0x9e, 0xf7, 0x8c, 0xbe, 0x3f, 0xa9, 0xe7, 0x3c, 0x7f, 0x07, 0x00,
	0x00, 0xff, 0xff, 0xef, 0x1b, 0xed, 0x16, 0x08, 0x01, 0x00, 0x00,
}
