// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_index.proto

package cds_cabinet_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IndexGetRequest struct {
	Index                *Index   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexGetRequest) Reset()         { *m = IndexGetRequest{} }
func (m *IndexGetRequest) String() string { return proto.CompactTextString(m) }
func (*IndexGetRequest) ProtoMessage()    {}
func (*IndexGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46e40c52b04100e5, []int{0}
}

func (m *IndexGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexGetRequest.Unmarshal(m, b)
}
func (m *IndexGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexGetRequest.Marshal(b, m, deterministic)
}
func (m *IndexGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexGetRequest.Merge(m, src)
}
func (m *IndexGetRequest) XXX_Size() int {
	return xxx_messageInfo_IndexGetRequest.Size(m)
}
func (m *IndexGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexGetRequest proto.InternalMessageInfo

func (m *IndexGetRequest) GetIndex() *Index {
	if m != nil {
		return m.Index
	}
	return nil
}

type IndexListRequest struct {
	Opt                  *ListOptions `protobuf:"bytes,1,opt,name=opt,proto3" json:"opt,omitempty"`
	Index                uint32       `protobuf:"varint,10,opt,name=index,proto3" json:"index,omitempty"`
	Value                string       `protobuf:"bytes,11,opt,name=value,proto3" json:"value,omitempty"`
	IncludeIndex         bool         `protobuf:"varint,20,opt,name=include_index,json=includeIndex,proto3" json:"include_index,omitempty"`
	IncludeValue         bool         `protobuf:"varint,21,opt,name=include_value,json=includeValue,proto3" json:"include_value,omitempty"`
	IncludeProp          bool         `protobuf:"varint,22,opt,name=include_prop,json=includeProp,proto3" json:"include_prop,omitempty"`
	IncludeNode          bool         `protobuf:"varint,23,opt,name=include_node,json=includeNode,proto3" json:"include_node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *IndexListRequest) Reset()         { *m = IndexListRequest{} }
func (m *IndexListRequest) String() string { return proto.CompactTextString(m) }
func (*IndexListRequest) ProtoMessage()    {}
func (*IndexListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46e40c52b04100e5, []int{1}
}

func (m *IndexListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexListRequest.Unmarshal(m, b)
}
func (m *IndexListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexListRequest.Marshal(b, m, deterministic)
}
func (m *IndexListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexListRequest.Merge(m, src)
}
func (m *IndexListRequest) XXX_Size() int {
	return xxx_messageInfo_IndexListRequest.Size(m)
}
func (m *IndexListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexListRequest proto.InternalMessageInfo

func (m *IndexListRequest) GetOpt() *ListOptions {
	if m != nil {
		return m.Opt
	}
	return nil
}

func (m *IndexListRequest) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *IndexListRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *IndexListRequest) GetIncludeIndex() bool {
	if m != nil {
		return m.IncludeIndex
	}
	return false
}

func (m *IndexListRequest) GetIncludeValue() bool {
	if m != nil {
		return m.IncludeValue
	}
	return false
}

func (m *IndexListRequest) GetIncludeProp() bool {
	if m != nil {
		return m.IncludeProp
	}
	return false
}

func (m *IndexListRequest) GetIncludeNode() bool {
	if m != nil {
		return m.IncludeNode
	}
	return false
}

type IndexChoiceRequest struct {
	Opt                  *ListOptions `protobuf:"bytes,1,opt,name=opt,proto3" json:"opt,omitempty"`
	Index                uint32       `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *IndexChoiceRequest) Reset()         { *m = IndexChoiceRequest{} }
func (m *IndexChoiceRequest) String() string { return proto.CompactTextString(m) }
func (*IndexChoiceRequest) ProtoMessage()    {}
func (*IndexChoiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46e40c52b04100e5, []int{2}
}

func (m *IndexChoiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexChoiceRequest.Unmarshal(m, b)
}
func (m *IndexChoiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexChoiceRequest.Marshal(b, m, deterministic)
}
func (m *IndexChoiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexChoiceRequest.Merge(m, src)
}
func (m *IndexChoiceRequest) XXX_Size() int {
	return xxx_messageInfo_IndexChoiceRequest.Size(m)
}
func (m *IndexChoiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexChoiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexChoiceRequest proto.InternalMessageInfo

func (m *IndexChoiceRequest) GetOpt() *ListOptions {
	if m != nil {
		return m.Opt
	}
	return nil
}

func (m *IndexChoiceRequest) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*IndexGetRequest)(nil), "cds.cabinet.v1.IndexGetRequest")
	proto.RegisterType((*IndexListRequest)(nil), "cds.cabinet.v1.IndexListRequest")
	proto.RegisterType((*IndexChoiceRequest)(nil), "cds.cabinet.v1.IndexChoiceRequest")
}

func init() { proto.RegisterFile("service_index.proto", fileDescriptor_46e40c52b04100e5) }

var fileDescriptor_46e40c52b04100e5 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0x87, 0x89, 0xa2, 0x68, 0xba, 0xa9, 0xc4, 0x4d, 0xc3, 0xbc, 0xd4, 0x7a, 0x29, 0x88, 0x01,
	0xf5, 0xee, 0xc5, 0x83, 0x08, 0xa2, 0x92, 0x83, 0xe0, 0x69, 0x74, 0xc9, 0x83, 0x05, 0x46, 0x12,
	0x93, 0xb4, 0xf8, 0xcf, 0x0b, 0xd2, 0x34, 0x95, 0xd6, 0xeb, 0x8e, 0xef, 0x97, 0xef, 0x7d, 0x2f,
	0x79, 0xc1, 0xa7, 0x1e, 0x5c, 0xa3, 0x04, 0x2c, 0x95, 0x96, 0xf0, 0xcd, 0xac, 0x33, 0xc1, 0x90,
	0x23, 0x21, 0x3d, 0x13, 0xd5, 0x4a, 0x69, 0x08, 0xac, 0xb9, 0x5d, 0x4c, 0xfc, 0xba, 0x72, 0x20,
	0xbb, 0xd3, 0x45, 0x36, 0x40, 0x8b, 0x07, 0x7c, 0xfc, 0xdc, 0x96, 0x4f, 0x10, 0x38, 0x7c, 0xd5,
	0xe0, 0x03, 0xb9, 0xc6, 0x7b, 0x91, 0xa0, 0x28, 0x47, 0x65, 0x76, 0x37, 0x67, 0x63, 0x1b, 0x8b,
	0x3c, 0xef, 0x98, 0xe2, 0x07, 0xe1, 0x93, 0x18, 0xbc, 0x28, 0xff, 0x67, 0xb8, 0xc1, 0xbb, 0xc6,
	0x86, 0xd4, 0x7f, 0xf1, 0xbf, 0xbf, 0x25, 0xdf, 0x6c, 0x50, 0x46, 0x7b, 0xde, 0x72, 0x64, 0xd6,
	0x0f, 0xc4, 0x39, 0x2a, 0xa7, 0xc9, 0xdc, 0xa6, 0x4d, 0xb5, 0xa9, 0x81, 0x66, 0x39, 0x2a, 0x0f,
	0x79, 0x57, 0x90, 0x2b, 0x3c, 0x55, 0x5a, 0x6c, 0x6a, 0x99, 0x5e, 0x4c, 0x67, 0x39, 0x2a, 0x0f,
	0xf8, 0x24, 0x85, 0xf1, 0x2a, 0x43, 0xa8, 0x53, 0xcc, 0x47, 0xd0, 0x47, 0x34, 0x5d, 0xe2, 0xbe,
	0x5e, 0x5a, 0x67, 0x2c, 0x3d, 0x8b, 0x4c, 0x96, 0xb2, 0x77, 0x67, 0xec, 0x10, 0xd1, 0x46, 0x02,
	0x3d, 0x1f, 0x21, 0xaf, 0x46, 0x42, 0xf1, 0x89, 0x49, 0x9c, 0xf9, 0xb8, 0x36, 0x4a, 0xc0, 0xb6,
	0x0b, 0xd8, 0x19, 0x2c, 0x60, 0xb5, 0x1f, 0x7f, 0xe8, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0x77,
	0x26, 0xb7, 0x38, 0xe3, 0x01, 0x00, 0x00,
}
