// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_meta.proto

package cds_cabinet_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MetaGetResponse struct {
	Val                  []byte   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaGetResponse) Reset()         { *m = MetaGetResponse{} }
func (m *MetaGetResponse) String() string { return proto.CompactTextString(m) }
func (*MetaGetResponse) ProtoMessage()    {}
func (*MetaGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9788f851de37978a, []int{0}
}

func (m *MetaGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaGetResponse.Unmarshal(m, b)
}
func (m *MetaGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaGetResponse.Marshal(b, m, deterministic)
}
func (m *MetaGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaGetResponse.Merge(m, src)
}
func (m *MetaGetResponse) XXX_Size() int {
	return xxx_messageInfo_MetaGetResponse.Size(m)
}
func (m *MetaGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetaGetResponse proto.InternalMessageInfo

func (m *MetaGetResponse) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

type MetaListRequest struct {
	Opt                  *ListOptions `protobuf:"bytes,1,opt,name=opt,proto3" json:"opt,omitempty"`
	Meta                 *Meta        `protobuf:"bytes,10,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MetaListRequest) Reset()         { *m = MetaListRequest{} }
func (m *MetaListRequest) String() string { return proto.CompactTextString(m) }
func (*MetaListRequest) ProtoMessage()    {}
func (*MetaListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9788f851de37978a, []int{1}
}

func (m *MetaListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaListRequest.Unmarshal(m, b)
}
func (m *MetaListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaListRequest.Marshal(b, m, deterministic)
}
func (m *MetaListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaListRequest.Merge(m, src)
}
func (m *MetaListRequest) XXX_Size() int {
	return xxx_messageInfo_MetaListRequest.Size(m)
}
func (m *MetaListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetaListRequest proto.InternalMessageInfo

func (m *MetaListRequest) GetOpt() *ListOptions {
	if m != nil {
		return m.Opt
	}
	return nil
}

func (m *MetaListRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*MetaGetResponse)(nil), "cds.cabinet.v1.MetaGetResponse")
	proto.RegisterType((*MetaListRequest)(nil), "cds.cabinet.v1.MetaListRequest")
}

func init() { proto.RegisterFile("service_meta.proto", fileDescriptor_9788f851de37978a) }

var fileDescriptor_9788f851de37978a = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xce, 0xb1, 0xca, 0xc2, 0x30,
	0x10, 0xc0, 0x71, 0x4a, 0x3f, 0xbe, 0xe1, 0x2c, 0x2a, 0xc1, 0xa1, 0xd4, 0x45, 0xea, 0xd2, 0xc5,
	0x80, 0xfa, 0x10, 0x2e, 0x8a, 0x90, 0x17, 0x90, 0xb4, 0x3d, 0x30, 0xa2, 0x4d, 0xcc, 0x9d, 0x79,
	0x7e, 0x49, 0x3a, 0x88, 0x6e, 0x07, 0xf7, 0xe3, 0xfe, 0x07, 0x82, 0xd0, 0x07, 0xd3, 0xe1, 0xe5,
	0x81, 0xac, 0xa5, 0xf3, 0x96, 0xad, 0x98, 0x76, 0x3d, 0xc9, 0x4e, 0xb7, 0x66, 0x40, 0x96, 0x61,
	0x5b, 0x15, 0x74, 0xd5, 0x1e, 0xfb, 0x71, 0x5b, 0xc1, 0x47, 0xd6, 0x6b, 0x98, 0x9d, 0x90, 0xf5,
	0x01, 0x59, 0x21, 0x39, 0x3b, 0x10, 0x8a, 0x39, 0xe4, 0x41, 0xdf, 0xcb, 0x6c, 0x95, 0x35, 0x85,
	0x8a, 0x63, 0x7d, 0x1b, 0xd1, 0xd1, 0x10, 0x2b, 0x7c, 0xbe, 0x90, 0x58, 0x6c, 0x20, 0xb7, 0x8e,
	0x13, 0x9a, 0xec, 0x96, 0xf2, 0xbb, 0x27, 0xa3, 0x3c, 0x3b, 0x36, 0x76, 0x20, 0x15, 0x9d, 0x68,
	0xe0, 0x2f, 0x46, 0x4b, 0x48, 0x7e, 0xf1, 0xeb, 0xe3, 0x75, 0x95, 0x44, 0xfb, 0x9f, 0xfe, 0xda,
	0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x13, 0x26, 0xd8, 0x98, 0xd7, 0x00, 0x00, 0x00,
}
