// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_transaction.proto

package cds_cabinet_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionAction struct {
	// Types that are valid to be assigned to Action:
	//	*TransactionAction_CounterIncrement
	//	*TransactionAction_CounterDelete
	//	*TransactionAction_CounterRegister
	//	*TransactionAction_EdgeUpdate
	//	*TransactionAction_EdgeDelete
	//	*TransactionAction_EdgeClear
	//	*TransactionAction_IndexCreate
	//	*TransactionAction_IndexDelete
	//	*TransactionAction_MetaUpdate
	//	*TransactionAction_MetaDelete
	//	*TransactionAction_MetaClear
	//	*TransactionAction_NodeCreate
	//	*TransactionAction_NodeUpdate
	//	*TransactionAction_NodeDelete
	//	*TransactionAction_ReadCheck
	Action               isTransactionAction_Action `protobuf_oneof:"action"`
	ActionId             uint32                     `protobuf:"varint,80,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *TransactionAction) Reset()         { *m = TransactionAction{} }
func (m *TransactionAction) String() string { return proto.CompactTextString(m) }
func (*TransactionAction) ProtoMessage()    {}
func (*TransactionAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_eae9ea52da333b22, []int{0}
}

func (m *TransactionAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionAction.Unmarshal(m, b)
}
func (m *TransactionAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionAction.Marshal(b, m, deterministic)
}
func (m *TransactionAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionAction.Merge(m, src)
}
func (m *TransactionAction) XXX_Size() int {
	return xxx_messageInfo_TransactionAction.Size(m)
}
func (m *TransactionAction) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionAction.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionAction proto.InternalMessageInfo

type isTransactionAction_Action interface {
	isTransactionAction_Action()
}

type TransactionAction_CounterIncrement struct {
	CounterIncrement *Counter `protobuf:"bytes,1,opt,name=counter_increment,json=counterIncrement,proto3,oneof"`
}

type TransactionAction_CounterDelete struct {
	CounterDelete *Counter `protobuf:"bytes,2,opt,name=counter_delete,json=counterDelete,proto3,oneof"`
}

type TransactionAction_CounterRegister struct {
	CounterRegister *Counter `protobuf:"bytes,3,opt,name=counter_register,json=counterRegister,proto3,oneof"`
}

type TransactionAction_EdgeUpdate struct {
	EdgeUpdate *Edge `protobuf:"bytes,11,opt,name=edge_update,json=edgeUpdate,proto3,oneof"`
}

type TransactionAction_EdgeDelete struct {
	EdgeDelete *Edge `protobuf:"bytes,12,opt,name=edge_delete,json=edgeDelete,proto3,oneof"`
}

type TransactionAction_EdgeClear struct {
	EdgeClear *Edge `protobuf:"bytes,13,opt,name=edge_clear,json=edgeClear,proto3,oneof"`
}

type TransactionAction_IndexCreate struct {
	IndexCreate *Index `protobuf:"bytes,21,opt,name=index_create,json=indexCreate,proto3,oneof"`
}

type TransactionAction_IndexDelete struct {
	IndexDelete *Index `protobuf:"bytes,22,opt,name=index_delete,json=indexDelete,proto3,oneof"`
}

type TransactionAction_MetaUpdate struct {
	MetaUpdate *Meta `protobuf:"bytes,31,opt,name=meta_update,json=metaUpdate,proto3,oneof"`
}

type TransactionAction_MetaDelete struct {
	MetaDelete *Meta `protobuf:"bytes,32,opt,name=meta_delete,json=metaDelete,proto3,oneof"`
}

type TransactionAction_MetaClear struct {
	MetaClear *Meta `protobuf:"bytes,33,opt,name=meta_clear,json=metaClear,proto3,oneof"`
}

type TransactionAction_NodeCreate struct {
	NodeCreate *Node `protobuf:"bytes,40,opt,name=node_create,json=nodeCreate,proto3,oneof"`
}

type TransactionAction_NodeUpdate struct {
	NodeUpdate *Node `protobuf:"bytes,41,opt,name=node_update,json=nodeUpdate,proto3,oneof"`
}

type TransactionAction_NodeDelete struct {
	NodeDelete *Node `protobuf:"bytes,42,opt,name=node_delete,json=nodeDelete,proto3,oneof"`
}

type TransactionAction_ReadCheck struct {
	ReadCheck *ReadCheckRequest `protobuf:"bytes,50,opt,name=read_check,json=readCheck,proto3,oneof"`
}

func (*TransactionAction_CounterIncrement) isTransactionAction_Action() {}

func (*TransactionAction_CounterDelete) isTransactionAction_Action() {}

func (*TransactionAction_CounterRegister) isTransactionAction_Action() {}

func (*TransactionAction_EdgeUpdate) isTransactionAction_Action() {}

func (*TransactionAction_EdgeDelete) isTransactionAction_Action() {}

func (*TransactionAction_EdgeClear) isTransactionAction_Action() {}

func (*TransactionAction_IndexCreate) isTransactionAction_Action() {}

func (*TransactionAction_IndexDelete) isTransactionAction_Action() {}

func (*TransactionAction_MetaUpdate) isTransactionAction_Action() {}

func (*TransactionAction_MetaDelete) isTransactionAction_Action() {}

func (*TransactionAction_MetaClear) isTransactionAction_Action() {}

func (*TransactionAction_NodeCreate) isTransactionAction_Action() {}

func (*TransactionAction_NodeUpdate) isTransactionAction_Action() {}

func (*TransactionAction_NodeDelete) isTransactionAction_Action() {}

func (*TransactionAction_ReadCheck) isTransactionAction_Action() {}

func (m *TransactionAction) GetAction() isTransactionAction_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *TransactionAction) GetCounterIncrement() *Counter {
	if x, ok := m.GetAction().(*TransactionAction_CounterIncrement); ok {
		return x.CounterIncrement
	}
	return nil
}

func (m *TransactionAction) GetCounterDelete() *Counter {
	if x, ok := m.GetAction().(*TransactionAction_CounterDelete); ok {
		return x.CounterDelete
	}
	return nil
}

func (m *TransactionAction) GetCounterRegister() *Counter {
	if x, ok := m.GetAction().(*TransactionAction_CounterRegister); ok {
		return x.CounterRegister
	}
	return nil
}

func (m *TransactionAction) GetEdgeUpdate() *Edge {
	if x, ok := m.GetAction().(*TransactionAction_EdgeUpdate); ok {
		return x.EdgeUpdate
	}
	return nil
}

func (m *TransactionAction) GetEdgeDelete() *Edge {
	if x, ok := m.GetAction().(*TransactionAction_EdgeDelete); ok {
		return x.EdgeDelete
	}
	return nil
}

func (m *TransactionAction) GetEdgeClear() *Edge {
	if x, ok := m.GetAction().(*TransactionAction_EdgeClear); ok {
		return x.EdgeClear
	}
	return nil
}

func (m *TransactionAction) GetIndexCreate() *Index {
	if x, ok := m.GetAction().(*TransactionAction_IndexCreate); ok {
		return x.IndexCreate
	}
	return nil
}

func (m *TransactionAction) GetIndexDelete() *Index {
	if x, ok := m.GetAction().(*TransactionAction_IndexDelete); ok {
		return x.IndexDelete
	}
	return nil
}

func (m *TransactionAction) GetMetaUpdate() *Meta {
	if x, ok := m.GetAction().(*TransactionAction_MetaUpdate); ok {
		return x.MetaUpdate
	}
	return nil
}

func (m *TransactionAction) GetMetaDelete() *Meta {
	if x, ok := m.GetAction().(*TransactionAction_MetaDelete); ok {
		return x.MetaDelete
	}
	return nil
}

func (m *TransactionAction) GetMetaClear() *Meta {
	if x, ok := m.GetAction().(*TransactionAction_MetaClear); ok {
		return x.MetaClear
	}
	return nil
}

func (m *TransactionAction) GetNodeCreate() *Node {
	if x, ok := m.GetAction().(*TransactionAction_NodeCreate); ok {
		return x.NodeCreate
	}
	return nil
}

func (m *TransactionAction) GetNodeUpdate() *Node {
	if x, ok := m.GetAction().(*TransactionAction_NodeUpdate); ok {
		return x.NodeUpdate
	}
	return nil
}

func (m *TransactionAction) GetNodeDelete() *Node {
	if x, ok := m.GetAction().(*TransactionAction_NodeDelete); ok {
		return x.NodeDelete
	}
	return nil
}

func (m *TransactionAction) GetReadCheck() *ReadCheckRequest {
	if x, ok := m.GetAction().(*TransactionAction_ReadCheck); ok {
		return x.ReadCheck
	}
	return nil
}

func (m *TransactionAction) GetActionId() uint32 {
	if m != nil {
		return m.ActionId
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TransactionAction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TransactionAction_CounterIncrement)(nil),
		(*TransactionAction_CounterDelete)(nil),
		(*TransactionAction_CounterRegister)(nil),
		(*TransactionAction_EdgeUpdate)(nil),
		(*TransactionAction_EdgeDelete)(nil),
		(*TransactionAction_EdgeClear)(nil),
		(*TransactionAction_IndexCreate)(nil),
		(*TransactionAction_IndexDelete)(nil),
		(*TransactionAction_MetaUpdate)(nil),
		(*TransactionAction_MetaDelete)(nil),
		(*TransactionAction_MetaClear)(nil),
		(*TransactionAction_NodeCreate)(nil),
		(*TransactionAction_NodeUpdate)(nil),
		(*TransactionAction_NodeDelete)(nil),
		(*TransactionAction_ReadCheck)(nil),
	}
}

type TransactionActionResponse struct {
	Status   MutationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=cds.cabinet.v1.MutationStatus" json:"status,omitempty"`
	ActionId uint32         `protobuf:"varint,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Error    string         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Response:
	//	*TransactionActionResponse_NodeCreate
	//	*TransactionActionResponse_ReadCheck
	Response             isTransactionActionResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *TransactionActionResponse) Reset()         { *m = TransactionActionResponse{} }
func (m *TransactionActionResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionActionResponse) ProtoMessage()    {}
func (*TransactionActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eae9ea52da333b22, []int{1}
}

func (m *TransactionActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionActionResponse.Unmarshal(m, b)
}
func (m *TransactionActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionActionResponse.Marshal(b, m, deterministic)
}
func (m *TransactionActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionActionResponse.Merge(m, src)
}
func (m *TransactionActionResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionActionResponse.Size(m)
}
func (m *TransactionActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionActionResponse proto.InternalMessageInfo

func (m *TransactionActionResponse) GetStatus() MutationStatus {
	if m != nil {
		return m.Status
	}
	return MutationStatus_SUCCESS
}

func (m *TransactionActionResponse) GetActionId() uint32 {
	if m != nil {
		return m.ActionId
	}
	return 0
}

func (m *TransactionActionResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type isTransactionActionResponse_Response interface {
	isTransactionActionResponse_Response()
}

type TransactionActionResponse_NodeCreate struct {
	NodeCreate *NodeCreateResponse `protobuf:"bytes,20,opt,name=node_create,json=nodeCreate,proto3,oneof"`
}

type TransactionActionResponse_ReadCheck struct {
	ReadCheck *ReadCheckResponse `protobuf:"bytes,30,opt,name=read_check,json=readCheck,proto3,oneof"`
}

func (*TransactionActionResponse_NodeCreate) isTransactionActionResponse_Response() {}

func (*TransactionActionResponse_ReadCheck) isTransactionActionResponse_Response() {}

func (m *TransactionActionResponse) GetResponse() isTransactionActionResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *TransactionActionResponse) GetNodeCreate() *NodeCreateResponse {
	if x, ok := m.GetResponse().(*TransactionActionResponse_NodeCreate); ok {
		return x.NodeCreate
	}
	return nil
}

func (m *TransactionActionResponse) GetReadCheck() *ReadCheckResponse {
	if x, ok := m.GetResponse().(*TransactionActionResponse_ReadCheck); ok {
		return x.ReadCheck
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TransactionActionResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TransactionActionResponse_NodeCreate)(nil),
		(*TransactionActionResponse_ReadCheck)(nil),
	}
}

type ReadCheckRequest struct {
	Source               string         `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Operator             CheckOperators `protobuf:"varint,2,opt,name=operator,proto3,enum=cds.cabinet.v1.CheckOperators" json:"operator,omitempty"`
	Target               *CheckTarget   `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReadCheckRequest) Reset()         { *m = ReadCheckRequest{} }
func (m *ReadCheckRequest) String() string { return proto.CompactTextString(m) }
func (*ReadCheckRequest) ProtoMessage()    {}
func (*ReadCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eae9ea52da333b22, []int{2}
}

func (m *ReadCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadCheckRequest.Unmarshal(m, b)
}
func (m *ReadCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadCheckRequest.Marshal(b, m, deterministic)
}
func (m *ReadCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadCheckRequest.Merge(m, src)
}
func (m *ReadCheckRequest) XXX_Size() int {
	return xxx_messageInfo_ReadCheckRequest.Size(m)
}
func (m *ReadCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadCheckRequest proto.InternalMessageInfo

func (m *ReadCheckRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *ReadCheckRequest) GetOperator() CheckOperators {
	if m != nil {
		return m.Operator
	}
	return CheckOperators_EXISTS
}

func (m *ReadCheckRequest) GetTarget() *CheckTarget {
	if m != nil {
		return m.Target
	}
	return nil
}

type ReadCheckResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadCheckResponse) Reset()         { *m = ReadCheckResponse{} }
func (m *ReadCheckResponse) String() string { return proto.CompactTextString(m) }
func (*ReadCheckResponse) ProtoMessage()    {}
func (*ReadCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eae9ea52da333b22, []int{3}
}

func (m *ReadCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadCheckResponse.Unmarshal(m, b)
}
func (m *ReadCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadCheckResponse.Marshal(b, m, deterministic)
}
func (m *ReadCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadCheckResponse.Merge(m, src)
}
func (m *ReadCheckResponse) XXX_Size() int {
	return xxx_messageInfo_ReadCheckResponse.Size(m)
}
func (m *ReadCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadCheckResponse proto.InternalMessageInfo

func (m *ReadCheckResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type CheckTarget struct {
	// Types that are valid to be assigned to Target:
	//	*CheckTarget_Val
	//	*CheckTarget_Iri
	Target               isCheckTarget_Target `protobuf_oneof:"target"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CheckTarget) Reset()         { *m = CheckTarget{} }
func (m *CheckTarget) String() string { return proto.CompactTextString(m) }
func (*CheckTarget) ProtoMessage()    {}
func (*CheckTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_eae9ea52da333b22, []int{4}
}

func (m *CheckTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTarget.Unmarshal(m, b)
}
func (m *CheckTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTarget.Marshal(b, m, deterministic)
}
func (m *CheckTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTarget.Merge(m, src)
}
func (m *CheckTarget) XXX_Size() int {
	return xxx_messageInfo_CheckTarget.Size(m)
}
func (m *CheckTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTarget.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTarget proto.InternalMessageInfo

type isCheckTarget_Target interface {
	isCheckTarget_Target()
}

type CheckTarget_Val struct {
	Val string `protobuf:"bytes,1,opt,name=val,proto3,oneof"`
}

type CheckTarget_Iri struct {
	Iri string `protobuf:"bytes,2,opt,name=iri,proto3,oneof"`
}

func (*CheckTarget_Val) isCheckTarget_Target() {}

func (*CheckTarget_Iri) isCheckTarget_Target() {}

func (m *CheckTarget) GetTarget() isCheckTarget_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *CheckTarget) GetVal() string {
	if x, ok := m.GetTarget().(*CheckTarget_Val); ok {
		return x.Val
	}
	return ""
}

func (m *CheckTarget) GetIri() string {
	if x, ok := m.GetTarget().(*CheckTarget_Iri); ok {
		return x.Iri
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CheckTarget) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CheckTarget_Val)(nil),
		(*CheckTarget_Iri)(nil),
	}
}

func init() {
	proto.RegisterType((*TransactionAction)(nil), "cds.cabinet.v1.TransactionAction")
	proto.RegisterType((*TransactionActionResponse)(nil), "cds.cabinet.v1.TransactionActionResponse")
	proto.RegisterType((*ReadCheckRequest)(nil), "cds.cabinet.v1.ReadCheckRequest")
	proto.RegisterType((*ReadCheckResponse)(nil), "cds.cabinet.v1.ReadCheckResponse")
	proto.RegisterType((*CheckTarget)(nil), "cds.cabinet.v1.CheckTarget")
}

func init() { proto.RegisterFile("service_transaction.proto", fileDescriptor_eae9ea52da333b22) }

var fileDescriptor_eae9ea52da333b22 = []byte{
	// 656 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x5f, 0x4f, 0xdb, 0x3c,
	0x14, 0xc6, 0x5b, 0xd0, 0xdb, 0xb7, 0x3d, 0x01, 0x06, 0x1e, 0xb0, 0x00, 0x12, 0x2b, 0xbd, 0x62,
	0x9b, 0x54, 0x69, 0xa0, 0x0d, 0x89, 0x9b, 0x0d, 0x0a, 0x53, 0xb9, 0xd8, 0x1f, 0x79, 0xec, 0x3a,
	0x32, 0xf1, 0x51, 0x89, 0x56, 0x92, 0xce, 0x76, 0xd0, 0xbe, 0xcb, 0xb4, 0x2f, 0xb3, 0x4f, 0x36,
	0xf9, 0xd8, 0xa6, 0x6d, 0xa8, 0xda, 0xdd, 0x54, 0xf1, 0xe9, 0xf3, 0x7b, 0x7c, 0xce, 0xe3, 0x38,
	0xb0, 0xa3, 0x51, 0xdd, 0x67, 0x29, 0x26, 0x46, 0x89, 0x5c, 0x8b, 0xd4, 0x64, 0x45, 0xde, 0x1d,
	0xa9, 0xc2, 0x14, 0x6c, 0x2d, 0x95, 0xba, 0x9b, 0x8a, 0x9b, 0x2c, 0x47, 0xd3, 0xbd, 0x7f, 0xbd,
	0xbb, 0x15, 0xa4, 0x69, 0x51, 0xe6, 0x06, 0x95, 0x93, 0xed, 0xb2, 0x50, 0x46, 0x39, 0x40, 0x5f,
	0x7b, 0x1a, 0x6a, 0x59, 0x2e, 0xf1, 0x67, 0x55, 0x78, 0x87, 0x46, 0x54, 0x6b, 0x79, 0x21, 0x03,
	0xbc, 0x3a, 0xed, 0x0f, 0x13, 0xbe, 0xd1, 0xa4, 0x1f, 0x4c, 0xf8, 0xc0, 0x04, 0x0f, 0xc5, 0xc8,
	0x68, 0xff, 0xbc, 0xa2, 0x6f, 0x85, 0x42, 0xe9, 0x56, 0x9d, 0x3f, 0xff, 0xc3, 0xc6, 0xf5, 0x78,
	0xce, 0x33, 0xfa, 0x65, 0x1f, 0x60, 0xc3, 0xef, 0x98, 0x64, 0x79, 0xaa, 0xf0, 0x0e, 0x73, 0x13,
	0xd7, 0xdb, 0xf5, 0xc3, 0xe8, 0xe8, 0x59, 0x77, 0x3a, 0x83, 0x6e, 0xcf, 0x09, 0xfb, 0x35, 0xbe,
	0xee, 0x99, 0xab, 0x80, 0xb0, 0xf7, 0xb0, 0x16, 0x7c, 0x24, 0x0e, 0xd1, 0x60, 0xbc, 0xb4, 0xc8,
	0x24, 0x8c, 0x7a, 0x41, 0x7a, 0x76, 0x01, 0xc1, 0x35, 0x51, 0x38, 0xc8, 0xb4, 0x41, 0x15, 0x2f,
	0x2f, 0xf2, 0x78, 0xe2, 0x11, 0xee, 0x09, 0x76, 0x02, 0x91, 0x8d, 0x2c, 0x29, 0x47, 0x52, 0x18,
	0x8c, 0x23, 0x32, 0xd8, 0xac, 0x1a, 0x5c, 0xca, 0x01, 0xf6, 0x6b, 0x9c, 0xd2, 0xfd, 0x46, 0xca,
	0x07, 0xd0, 0x77, 0xbf, 0xb2, 0x18, 0xf4, 0x7d, 0xbf, 0x01, 0x5a, 0x25, 0xe9, 0x10, 0x85, 0x8a,
	0x57, 0xe7, 0x72, 0x2d, 0xab, 0xec, 0x59, 0x21, 0x3b, 0x85, 0x15, 0x3a, 0xcf, 0x24, 0x55, 0x68,
	0x3b, 0xdd, 0x22, 0x70, 0xab, 0x0a, 0x5e, 0x59, 0x4d, 0xbf, 0xc6, 0xdd, 0xe1, 0xf7, 0x48, 0x3b,
	0x66, 0x7d, 0xb3, 0xdb, 0xff, 0xc2, 0xfa, 0x76, 0x4f, 0x20, 0xb2, 0xaf, 0x4e, 0x08, 0xe8, 0xf9,
	0xec, 0x7e, 0x3f, 0xa2, 0x11, 0x76, 0x4e, 0x2b, 0x1d, 0x07, 0x44, 0xa0, 0xdf, 0xb3, 0xbd, 0x18,
	0x1c, 0x07, 0x44, 0xa0, 0x0b, 0xe8, 0x60, 0x2e, 0xd7, 0xb2, 0x4a, 0x17, 0xd0, 0x09, 0x44, 0xf6,
	0xbd, 0x0e, 0xf9, 0x1c, 0xce, 0xe6, 0x3e, 0x15, 0x92, 0x0e, 0xc4, 0x4a, 0x7d, 0x3a, 0x01, 0xf4,
	0x13, 0xbe, 0x58, 0x0c, 0x8e, 0x27, 0x24, 0xd0, 0x4f, 0xf8, 0x72, 0x31, 0xe8, 0x27, 0x3c, 0x03,
	0x50, 0x28, 0x64, 0x92, 0xde, 0x62, 0xfa, 0x3d, 0x3e, 0x22, 0xae, 0x5d, 0xe5, 0x38, 0x0a, 0xd9,
	0xb3, 0x02, 0x8e, 0x3f, 0x4a, 0xd4, 0xc6, 0x4e, 0xab, 0x42, 0x8d, 0xed, 0x41, 0xcb, 0xdd, 0xcb,
	0x24, 0x93, 0xf1, 0x97, 0x76, 0xfd, 0x70, 0x95, 0x37, 0x5d, 0xe1, 0x4a, 0x9e, 0x37, 0xa1, 0xe1,
	0x9e, 0x3b, 0xbf, 0x97, 0x60, 0xe7, 0xd1, 0x25, 0xe6, 0xa8, 0x47, 0x45, 0xae, 0x91, 0xbd, 0x85,
	0x86, 0x36, 0xc2, 0x94, 0x9a, 0x6e, 0xf0, 0xda, 0xd1, 0xfe, 0xa3, 0x94, 0x4b, 0x23, 0x2c, 0xf1,
	0x95, 0x54, 0xdc, 0xab, 0xa7, 0x37, 0x5f, 0x9a, 0xde, 0x9c, 0x6d, 0xc2, 0x7f, 0xa8, 0x54, 0xe1,
	0x2e, 0x63, 0x8b, 0xbb, 0x05, 0xbb, 0x9c, 0x3e, 0x9d, 0x4d, 0x9a, 0xb9, 0x33, 0x2b, 0x2b, 0x77,
	0x2a, 0xa1, 0xc7, 0xca, 0x59, 0x9d, 0x4f, 0x25, 0xb7, 0x4f, 0x2e, 0x07, 0x73, 0x92, 0x7b, 0x30,
	0x19, 0x47, 0x77, 0x0e, 0xd0, 0x54, 0xfe, 0x8f, 0xce, 0xaf, 0x3a, 0xac, 0x57, 0x83, 0x66, 0xdb,
	0xd0, 0xd0, 0x45, 0xa9, 0x52, 0xa4, 0x58, 0x5a, 0xdc, 0xaf, 0xd8, 0x29, 0x34, 0x8b, 0x11, 0x2a,
	0x61, 0x0a, 0x45, 0x53, 0xcf, 0x08, 0x8c, 0x7c, 0x3e, 0x7b, 0x91, 0xe6, 0x0f, 0x7a, 0x76, 0x0c,
	0x0d, 0x23, 0xd4, 0x00, 0x8d, 0xff, 0x46, 0xed, 0xcd, 0x24, 0xaf, 0x49, 0xc2, 0xbd, 0xb4, 0xf3,
	0x0a, 0x36, 0x1e, 0xcd, 0x62, 0xbb, 0x53, 0xa8, 0xcb, 0xa1, 0xfb, 0xec, 0x36, 0xb9, 0x5f, 0x75,
	0xde, 0x41, 0x34, 0xe1, 0xc1, 0x18, 0x2c, 0xdf, 0x8b, 0xa1, 0x9b, 0xa0, 0x5f, 0xe3, 0x76, 0x61,
	0x6b, 0x99, 0xca, 0xa8, 0x77, 0xaa, 0x65, 0x2a, 0xb3, 0xef, 0x8a, 0xdb, 0xed, 0xa6, 0x41, 0xdf,
	0xfd, 0xe3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x06, 0xd0, 0x28, 0xe2, 0xe6, 0x06, 0x00, 0x00,
}
