// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_edge.proto

package cds_cabinet_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EdgeGetRequest struct {
	Edge                 *Edge    `protobuf:"bytes,2,opt,name=edge,proto3" json:"edge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EdgeGetRequest) Reset()         { *m = EdgeGetRequest{} }
func (m *EdgeGetRequest) String() string { return proto.CompactTextString(m) }
func (*EdgeGetRequest) ProtoMessage()    {}
func (*EdgeGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec6de44fafa439a, []int{0}
}

func (m *EdgeGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EdgeGetRequest.Unmarshal(m, b)
}
func (m *EdgeGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EdgeGetRequest.Marshal(b, m, deterministic)
}
func (m *EdgeGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdgeGetRequest.Merge(m, src)
}
func (m *EdgeGetRequest) XXX_Size() int {
	return xxx_messageInfo_EdgeGetRequest.Size(m)
}
func (m *EdgeGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EdgeGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EdgeGetRequest proto.InternalMessageInfo

func (m *EdgeGetRequest) GetEdge() *Edge {
	if m != nil {
		return m.Edge
	}
	return nil
}

type EdgeListRequest struct {
	Opt                  *ListOptions `protobuf:"bytes,1,opt,name=opt,proto3" json:"opt,omitempty"`
	Subject              string       `protobuf:"bytes,10,opt,name=subject,proto3" json:"subject,omitempty"`
	Predicate            uint32       `protobuf:"varint,11,opt,name=predicate,proto3" json:"predicate,omitempty"`
	IncludeSubject       bool         `protobuf:"varint,20,opt,name=include_subject,json=includeSubject,proto3" json:"include_subject,omitempty"`
	IncludePredicate     bool         `protobuf:"varint,21,opt,name=include_predicate,json=includePredicate,proto3" json:"include_predicate,omitempty"`
	IncludeTarget        bool         `protobuf:"varint,22,opt,name=include_target,json=includeTarget,proto3" json:"include_target,omitempty"`
	IncludeProp          bool         `protobuf:"varint,23,opt,name=include_prop,json=includeProp,proto3" json:"include_prop,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EdgeListRequest) Reset()         { *m = EdgeListRequest{} }
func (m *EdgeListRequest) String() string { return proto.CompactTextString(m) }
func (*EdgeListRequest) ProtoMessage()    {}
func (*EdgeListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec6de44fafa439a, []int{1}
}

func (m *EdgeListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EdgeListRequest.Unmarshal(m, b)
}
func (m *EdgeListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EdgeListRequest.Marshal(b, m, deterministic)
}
func (m *EdgeListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdgeListRequest.Merge(m, src)
}
func (m *EdgeListRequest) XXX_Size() int {
	return xxx_messageInfo_EdgeListRequest.Size(m)
}
func (m *EdgeListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EdgeListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EdgeListRequest proto.InternalMessageInfo

func (m *EdgeListRequest) GetOpt() *ListOptions {
	if m != nil {
		return m.Opt
	}
	return nil
}

func (m *EdgeListRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EdgeListRequest) GetPredicate() uint32 {
	if m != nil {
		return m.Predicate
	}
	return 0
}

func (m *EdgeListRequest) GetIncludeSubject() bool {
	if m != nil {
		return m.IncludeSubject
	}
	return false
}

func (m *EdgeListRequest) GetIncludePredicate() bool {
	if m != nil {
		return m.IncludePredicate
	}
	return false
}

func (m *EdgeListRequest) GetIncludeTarget() bool {
	if m != nil {
		return m.IncludeTarget
	}
	return false
}

func (m *EdgeListRequest) GetIncludeProp() bool {
	if m != nil {
		return m.IncludeProp
	}
	return false
}

func init() {
	proto.RegisterType((*EdgeGetRequest)(nil), "cds.cabinet.v1.EdgeGetRequest")
	proto.RegisterType((*EdgeListRequest)(nil), "cds.cabinet.v1.EdgeListRequest")
}

func init() { proto.RegisterFile("service_edge.proto", fileDescriptor_5ec6de44fafa439a) }

var fileDescriptor_5ec6de44fafa439a = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0x15, 0xb5, 0x93, 0x36, 0xd5, 0xa5, 0xea, 0x52, 0x3d, 0xc4, 0x82, 0x18, 0x10,
	0x03, 0xea, 0xcd, 0xbb, 0x78, 0x11, 0x94, 0xd5, 0x7b, 0x48, 0x76, 0x87, 0xb8, 0x22, 0xd9, 0x35,
	0x3b, 0xe9, 0x67, 0xf1, 0xe3, 0x4a, 0xd6, 0xfc, 0xc1, 0x1e, 0xe7, 0xbd, 0xdf, 0xfb, 0x1d, 0x06,
	0x98, 0xc3, 0x7a, 0xa3, 0x25, 0x66, 0xa8, 0x4a, 0x4c, 0x6d, 0x6d, 0xc8, 0xb0, 0x48, 0x2a, 0x97,
	0xca, 0xbc, 0xd0, 0x15, 0x52, 0xba, 0xb9, 0x5d, 0xcd, 0xdc, 0x47, 0x5e, 0xa3, 0xfa, 0x6b, 0x57,
	0x30, 0x92, 0xeb, 0x07, 0x88, 0x1e, 0x55, 0x89, 0x4f, 0x48, 0x02, 0xbf, 0x1b, 0x74, 0xc4, 0x12,
	0xd8, 0x6d, 0x7b, 0x3e, 0x89, 0x83, 0x24, 0xbc, 0x5b, 0xa6, 0xff, 0x55, 0x69, 0x4b, 0x0b, 0x4f,
	0xac, 0x7f, 0x26, 0xb0, 0x68, 0xcf, 0x67, 0xed, 0x86, 0xf5, 0x0d, 0xec, 0x18, 0x4b, 0x3c, 0xf0,
	0xe3, 0xb3, 0xed, 0x71, 0x4b, 0xbe, 0x58, 0xd2, 0xa6, 0x72, 0xa2, 0xe5, 0x18, 0x87, 0x7d, 0xd7,
	0x14, 0x9f, 0x28, 0x89, 0x43, 0x1c, 0x24, 0x53, 0xd1, 0x9f, 0xec, 0x1c, 0xa6, 0xb6, 0x46, 0xa5,
	0x65, 0x4e, 0xc8, 0xc3, 0x38, 0x48, 0xe6, 0x62, 0x0c, 0xd8, 0x15, 0x2c, 0x74, 0x25, 0xbf, 0x1a,
	0x85, 0x59, 0xbf, 0x5f, 0xc6, 0x41, 0x72, 0x20, 0xa2, 0x2e, 0x7e, 0xeb, 0x34, 0xd7, 0x70, 0xd4,
	0x83, 0xa3, 0xee, 0xd8, 0xa3, 0x87, 0x5d, 0xf1, 0x3a, 0x58, 0x2f, 0xa1, 0x9f, 0x67, 0x94, 0xd7,
	0x25, 0x12, 0x3f, 0xf1, 0xe4, 0xbc, 0x4b, 0xdf, 0x7d, 0xc8, 0x2e, 0x60, 0x36, 0x3a, 0x8d, 0xe5,
	0xa7, 0x1e, 0x0a, 0x07, 0x9d, 0xb1, 0xc5, 0x9e, 0xff, 0xee, 0xfd, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x14, 0x2c, 0xe4, 0xe4, 0x9d, 0x01, 0x00, 0x00,
}
