// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shared.proto

package cds_cabinet_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MutationStatus int32

const (
	MutationStatus_SUCCESS            MutationStatus = 0
	MutationStatus_GENERIC_FAILURE    MutationStatus = 10
	MutationStatus_CONNECTION_FAILURE MutationStatus = 11
	MutationStatus_PROCESSING_FAILURE MutationStatus = 12
	MutationStatus_READ_CHECK_FAILURE MutationStatus = 13
	MutationStatus_MUTATION_FAILURE   MutationStatus = 14
)

var MutationStatus_name = map[int32]string{
	0:  "SUCCESS",
	10: "GENERIC_FAILURE",
	11: "CONNECTION_FAILURE",
	12: "PROCESSING_FAILURE",
	13: "READ_CHECK_FAILURE",
	14: "MUTATION_FAILURE",
}

var MutationStatus_value = map[string]int32{
	"SUCCESS":            0,
	"GENERIC_FAILURE":    10,
	"CONNECTION_FAILURE": 11,
	"PROCESSING_FAILURE": 12,
	"READ_CHECK_FAILURE": 13,
	"MUTATION_FAILURE":   14,
}

func (x MutationStatus) String() string {
	return proto.EnumName(MutationStatus_name, int32(x))
}

func (MutationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d8a4e87e678c5ced, []int{0}
}

type RetrieveMode int32

const (
	RetrieveMode_ALL  RetrieveMode = 0
	RetrieveMode_PROP RetrieveMode = 2
	RetrieveMode_IDS  RetrieveMode = 3
)

var RetrieveMode_name = map[int32]string{
	0: "ALL",
	2: "PROP",
	3: "IDS",
}

var RetrieveMode_value = map[string]int32{
	"ALL":  0,
	"PROP": 2,
	"IDS":  3,
}

func (x RetrieveMode) String() string {
	return proto.EnumName(RetrieveMode_name, int32(x))
}

func (RetrieveMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d8a4e87e678c5ced, []int{1}
}

type ListOptions struct {
	Mode                 RetrieveMode `protobuf:"varint,1,opt,name=mode,proto3,enum=cds.cabinet.v1.RetrieveMode" json:"mode,omitempty"`
	ResumeAt             string       `protobuf:"bytes,2,opt,name=resume_at,json=resumeAt,proto3" json:"resume_at,omitempty"`
	PageSize             uint32       `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	KeyStart             string       `protobuf:"bytes,10,opt,name=key_start,json=keyStart,proto3" json:"key_start,omitempty"`
	KeyEnd               string       `protobuf:"bytes,11,opt,name=key_end,json=keyEnd,proto3" json:"key_end,omitempty"`
	Reverse              bool         `protobuf:"varint,12,opt,name=reverse,proto3" json:"reverse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListOptions) Reset()         { *m = ListOptions{} }
func (m *ListOptions) String() string { return proto.CompactTextString(m) }
func (*ListOptions) ProtoMessage()    {}
func (*ListOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a4e87e678c5ced, []int{0}
}

func (m *ListOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOptions.Unmarshal(m, b)
}
func (m *ListOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOptions.Marshal(b, m, deterministic)
}
func (m *ListOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOptions.Merge(m, src)
}
func (m *ListOptions) XXX_Size() int {
	return xxx_messageInfo_ListOptions.Size(m)
}
func (m *ListOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ListOptions proto.InternalMessageInfo

func (m *ListOptions) GetMode() RetrieveMode {
	if m != nil {
		return m.Mode
	}
	return RetrieveMode_ALL
}

func (m *ListOptions) GetResumeAt() string {
	if m != nil {
		return m.ResumeAt
	}
	return ""
}

func (m *ListOptions) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListOptions) GetKeyStart() string {
	if m != nil {
		return m.KeyStart
	}
	return ""
}

func (m *ListOptions) GetKeyEnd() string {
	if m != nil {
		return m.KeyEnd
	}
	return ""
}

func (m *ListOptions) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

type MutationResponse struct {
	Status               MutationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=cds.cabinet.v1.MutationStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MutationResponse) Reset()         { *m = MutationResponse{} }
func (m *MutationResponse) String() string { return proto.CompactTextString(m) }
func (*MutationResponse) ProtoMessage()    {}
func (*MutationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a4e87e678c5ced, []int{1}
}

func (m *MutationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutationResponse.Unmarshal(m, b)
}
func (m *MutationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutationResponse.Marshal(b, m, deterministic)
}
func (m *MutationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutationResponse.Merge(m, src)
}
func (m *MutationResponse) XXX_Size() int {
	return xxx_messageInfo_MutationResponse.Size(m)
}
func (m *MutationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MutationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MutationResponse proto.InternalMessageInfo

func (m *MutationResponse) GetStatus() MutationStatus {
	if m != nil {
		return m.Status
	}
	return MutationStatus_SUCCESS
}

func init() {
	proto.RegisterEnum("cds.cabinet.v1.MutationStatus", MutationStatus_name, MutationStatus_value)
	proto.RegisterEnum("cds.cabinet.v1.RetrieveMode", RetrieveMode_name, RetrieveMode_value)
	proto.RegisterType((*ListOptions)(nil), "cds.cabinet.v1.ListOptions")
	proto.RegisterType((*MutationResponse)(nil), "cds.cabinet.v1.MutationResponse")
}

func init() { proto.RegisterFile("shared.proto", fileDescriptor_d8a4e87e678c5ced) }

var fileDescriptor_d8a4e87e678c5ced = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcd, 0x0e, 0x9a, 0x40,
	0x14, 0x85, 0x45, 0x8d, 0xe0, 0x05, 0x29, 0x99, 0x36, 0x2d, 0x49, 0x9b, 0x86, 0xb8, 0x22, 0x2e,
	0x48, 0x7f, 0x92, 0xee, 0x09, 0x4e, 0x2d, 0x2d, 0x82, 0x19, 0x74, 0x4d, 0x50, 0x6e, 0x5a, 0x62,
	0x04, 0xc2, 0x8c, 0x26, 0xfa, 0x14, 0x7d, 0xad, 0xbe, 0x55, 0x33, 0xf8, 0x93, 0xda, 0xe5, 0xf9,
	0xce, 0x39, 0x93, 0x9c, 0xb9, 0x60, 0xf0, 0x5f, 0x79, 0x8b, 0x85, 0xd7, 0xb4, 0xb5, 0xa8, 0x89,
	0xb9, 0x2b, 0xb8, 0xb7, 0xcb, 0xb7, 0x65, 0x85, 0xc2, 0x3b, 0x7d, 0x9c, 0xfe, 0x51, 0x40, 0x8f,
	0x4a, 0x2e, 0x92, 0x46, 0x94, 0x75, 0xc5, 0xc9, 0x07, 0x18, 0x1e, 0xea, 0x02, 0x6d, 0xc5, 0x51,
	0x5c, 0xf3, 0xd3, 0x3b, 0xef, 0x39, 0xee, 0x31, 0x14, 0x6d, 0x89, 0x27, 0x5c, 0xd6, 0x05, 0xb2,
	0x2e, 0x49, 0xde, 0xc2, 0xb8, 0x45, 0x7e, 0x3c, 0x60, 0x96, 0x0b, 0xbb, 0xef, 0x28, 0xee, 0x98,
	0x69, 0x57, 0xe0, 0x0b, 0x69, 0x36, 0xf9, 0x4f, 0xcc, 0x78, 0x79, 0x41, 0x7b, 0xe0, 0x28, 0xee,
	0x84, 0x69, 0x12, 0xa4, 0xe5, 0xa5, 0x6b, 0xee, 0xf1, 0x9c, 0x71, 0x91, 0xb7, 0xc2, 0x86, 0x6b,
	0x73, 0x8f, 0xe7, 0x54, 0x6a, 0xf2, 0x06, 0x54, 0x69, 0x62, 0x55, 0xd8, 0x7a, 0x67, 0x8d, 0xf6,
	0x78, 0xa6, 0x55, 0x41, 0x6c, 0x50, 0x5b, 0x3c, 0x61, 0xcb, 0xd1, 0x36, 0x1c, 0xc5, 0xd5, 0xd8,
	0x5d, 0x4e, 0xbf, 0x83, 0xb5, 0x3c, 0x8a, 0x5c, 0x0e, 0x61, 0xc8, 0x9b, 0xba, 0xe2, 0x48, 0xbe,
	0xc0, 0x88, 0x8b, 0x5c, 0x1c, 0xf9, 0x6d, 0xd1, 0xfb, 0xff, 0x17, 0xdd, 0x1b, 0x69, 0x97, 0x62,
	0xb7, 0xf4, 0xec, 0xb7, 0x02, 0xe6, 0xb3, 0x45, 0x74, 0x50, 0xd3, 0x4d, 0x10, 0xd0, 0x34, 0xb5,
	0x7a, 0xe4, 0x25, 0xbc, 0x58, 0xd0, 0x98, 0xb2, 0x30, 0xc8, 0xbe, 0xfa, 0x61, 0xb4, 0x61, 0xd4,
	0x02, 0xf2, 0x1a, 0x48, 0x90, 0xc4, 0x31, 0x0d, 0xd6, 0x61, 0x12, 0x3f, 0xb8, 0x2e, 0xf9, 0x8a,
	0x25, 0xb2, 0x19, 0xc6, 0x8b, 0x07, 0x37, 0x24, 0x67, 0xd4, 0x9f, 0x67, 0xc1, 0x37, 0x1a, 0xfc,
	0x78, 0xf0, 0x09, 0x79, 0x05, 0xd6, 0x72, 0xb3, 0xf6, 0x9f, 0x5e, 0x31, 0x67, 0x33, 0x30, 0xfe,
	0xfd, 0x7e, 0xa2, 0xc2, 0xc0, 0x8f, 0x22, 0xab, 0x47, 0x34, 0x18, 0xae, 0x58, 0xb2, 0xb2, 0xfa,
	0x12, 0x85, 0xf3, 0xd4, 0x1a, 0x6c, 0x47, 0xdd, 0xb5, 0x3f, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0xea, 0x98, 0x9f, 0x9d, 0xfd, 0x01, 0x00, 0x00,
}
