// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shared.proto

package cds_cabinet_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MutationStatus int32

const (
	MutationStatus_SUCCESS            MutationStatus = 0
	MutationStatus_GENERIC_FAILURE    MutationStatus = 10
	MutationStatus_CONNECTION_FAILURE MutationStatus = 11
	MutationStatus_PROCESSING_FAILURE MutationStatus = 12
	MutationStatus_READ_CHECK_FAILURE MutationStatus = 13
	MutationStatus_MUTATION_FAILURE   MutationStatus = 14
)

var MutationStatus_name = map[int32]string{
	0:  "SUCCESS",
	10: "GENERIC_FAILURE",
	11: "CONNECTION_FAILURE",
	12: "PROCESSING_FAILURE",
	13: "READ_CHECK_FAILURE",
	14: "MUTATION_FAILURE",
}

var MutationStatus_value = map[string]int32{
	"SUCCESS":            0,
	"GENERIC_FAILURE":    10,
	"CONNECTION_FAILURE": 11,
	"PROCESSING_FAILURE": 12,
	"READ_CHECK_FAILURE": 13,
	"MUTATION_FAILURE":   14,
}

func (x MutationStatus) String() string {
	return proto.EnumName(MutationStatus_name, int32(x))
}

func (MutationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d8a4e87e678c5ced, []int{0}
}

type ListRange int32

const (
	ListRange_UNDEFINED   ListRange = 0
	ListRange_ALL         ListRange = 1
	ListRange_EXACT_RANGE ListRange = 2
	ListRange_START_WITH  ListRange = 3
)

var ListRange_name = map[int32]string{
	0: "UNDEFINED",
	1: "ALL",
	2: "EXACT_RANGE",
	3: "START_WITH",
}

var ListRange_value = map[string]int32{
	"UNDEFINED":   0,
	"ALL":         1,
	"EXACT_RANGE": 2,
	"START_WITH":  3,
}

func (x ListRange) String() string {
	return proto.EnumName(ListRange_name, int32(x))
}

func (ListRange) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d8a4e87e678c5ced, []int{1}
}

type ListOptions struct {
	PageSize             uint32    `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Mode                 ListRange `protobuf:"varint,4,opt,name=mode,proto3,enum=cds.cabinet.v1.ListRange" json:"mode,omitempty"`
	KeyStart             string    `protobuf:"bytes,10,opt,name=key_start,json=keyStart,proto3" json:"key_start,omitempty"`
	KeyEnd               string    `protobuf:"bytes,11,opt,name=key_end,json=keyEnd,proto3" json:"key_end,omitempty"`
	Reverse              bool      `protobuf:"varint,12,opt,name=reverse,proto3" json:"reverse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListOptions) Reset()         { *m = ListOptions{} }
func (m *ListOptions) String() string { return proto.CompactTextString(m) }
func (*ListOptions) ProtoMessage()    {}
func (*ListOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a4e87e678c5ced, []int{0}
}

func (m *ListOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOptions.Unmarshal(m, b)
}
func (m *ListOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOptions.Marshal(b, m, deterministic)
}
func (m *ListOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOptions.Merge(m, src)
}
func (m *ListOptions) XXX_Size() int {
	return xxx_messageInfo_ListOptions.Size(m)
}
func (m *ListOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ListOptions proto.InternalMessageInfo

func (m *ListOptions) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListOptions) GetMode() ListRange {
	if m != nil {
		return m.Mode
	}
	return ListRange_UNDEFINED
}

func (m *ListOptions) GetKeyStart() string {
	if m != nil {
		return m.KeyStart
	}
	return ""
}

func (m *ListOptions) GetKeyEnd() string {
	if m != nil {
		return m.KeyEnd
	}
	return ""
}

func (m *ListOptions) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

type MutationResponse struct {
	Status               MutationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=cds.cabinet.v1.MutationStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MutationResponse) Reset()         { *m = MutationResponse{} }
func (m *MutationResponse) String() string { return proto.CompactTextString(m) }
func (*MutationResponse) ProtoMessage()    {}
func (*MutationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a4e87e678c5ced, []int{1}
}

func (m *MutationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutationResponse.Unmarshal(m, b)
}
func (m *MutationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutationResponse.Marshal(b, m, deterministic)
}
func (m *MutationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutationResponse.Merge(m, src)
}
func (m *MutationResponse) XXX_Size() int {
	return xxx_messageInfo_MutationResponse.Size(m)
}
func (m *MutationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MutationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MutationResponse proto.InternalMessageInfo

func (m *MutationResponse) GetStatus() MutationStatus {
	if m != nil {
		return m.Status
	}
	return MutationStatus_SUCCESS
}

func init() {
	proto.RegisterEnum("cds.cabinet.v1.MutationStatus", MutationStatus_name, MutationStatus_value)
	proto.RegisterEnum("cds.cabinet.v1.ListRange", ListRange_name, ListRange_value)
	proto.RegisterType((*ListOptions)(nil), "cds.cabinet.v1.ListOptions")
	proto.RegisterType((*MutationResponse)(nil), "cds.cabinet.v1.MutationResponse")
}

func init() { proto.RegisterFile("shared.proto", fileDescriptor_d8a4e87e678c5ced) }

var fileDescriptor_d8a4e87e678c5ced = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0xc7, 0x3b, 0x6e, 0xd9, 0x8f, 0x93, 0xdd, 0x74, 0x18, 0x45, 0x23, 0x82, 0x2c, 0xbd, 0x0a,
	0x05, 0x03, 0x2a, 0x78, 0x1f, 0x26, 0xd3, 0x6d, 0x34, 0x9d, 0xc8, 0x24, 0x41, 0xef, 0x42, 0xda,
	0x1c, 0x6a, 0x58, 0x4c, 0x42, 0x66, 0x5a, 0xd8, 0x3e, 0x85, 0xaf, 0xe1, 0x5b, 0xca, 0x04, 0x1b,
	0xd8, 0x5e, 0x9e, 0xdf, 0xff, 0x83, 0x3f, 0x33, 0xb0, 0xd6, 0xbf, 0xaa, 0x01, 0xeb, 0xa0, 0x1f,
	0x3a, 0xd3, 0x31, 0xf7, 0xb6, 0xd6, 0xc1, 0x6d, 0x75, 0xd3, 0xb4, 0x68, 0x82, 0x87, 0x8f, 0xe7,
	0x7f, 0x09, 0x38, 0x49, 0xa3, 0x4d, 0xda, 0x9b, 0xa6, 0x6b, 0x35, 0x7b, 0x07, 0xab, 0xbe, 0xba,
	0xc3, 0x52, 0x37, 0x8f, 0xe8, 0xcd, 0xb6, 0xc4, 0xdf, 0xa8, 0xa5, 0x05, 0x59, 0xf3, 0x88, 0xec,
	0x03, 0x9c, 0xfe, 0xee, 0x6a, 0xf4, 0x4e, 0xb7, 0xc4, 0x77, 0x3f, 0xbd, 0x0d, 0x8e, 0xbb, 0x02,
	0xdb, 0xa3, 0xaa, 0xf6, 0x0e, 0xd5, 0x68, 0xb3, 0x5d, 0x7b, 0x3c, 0x94, 0xda, 0x54, 0x83, 0xf1,
	0x60, 0x4b, 0xfc, 0x95, 0x5a, 0xee, 0xf1, 0x90, 0xd9, 0x9b, 0xbd, 0x81, 0x85, 0x15, 0xb1, 0xad,
	0x3d, 0x67, 0x94, 0xe6, 0x7b, 0x3c, 0x88, 0xb6, 0x66, 0x1e, 0x2c, 0x06, 0x7c, 0xc0, 0x41, 0xa3,
	0xb7, 0xde, 0x12, 0x7f, 0xa9, 0x9e, 0xce, 0xf3, 0xaf, 0x40, 0xaf, 0xef, 0x4d, 0x65, 0x87, 0x2a,
	0xd4, 0x7d, 0xd7, 0x6a, 0x64, 0x5f, 0x60, 0xae, 0x4d, 0x65, 0xee, 0xb5, 0x47, 0xc6, 0x51, 0xef,
	0x9f, 0x8f, 0x7a, 0x4a, 0x64, 0xa3, 0x4b, 0xfd, 0x77, 0x5f, 0xfc, 0x21, 0xe0, 0x1e, 0x4b, 0xcc,
	0x81, 0x45, 0x56, 0x70, 0x2e, 0xb2, 0x8c, 0x9e, 0xb0, 0x97, 0x70, 0xb6, 0x13, 0x52, 0xa8, 0x98,
	0x97, 0x97, 0x61, 0x9c, 0x14, 0x4a, 0x50, 0x60, 0xaf, 0x81, 0xf1, 0x54, 0x4a, 0xc1, 0xf3, 0x38,
	0x95, 0x13, 0x77, 0x2c, 0xff, 0xae, 0x52, 0x9b, 0x8c, 0xe5, 0x6e, 0xe2, 0x6b, 0xcb, 0x95, 0x08,
	0xa3, 0x92, 0x5f, 0x09, 0xfe, 0x6d, 0xe2, 0x1b, 0xf6, 0x0a, 0xe8, 0x75, 0x91, 0x87, 0x47, 0x2d,
	0xee, 0x45, 0x04, 0xab, 0xe9, 0x05, 0xd9, 0x06, 0x56, 0x85, 0x8c, 0xc4, 0x65, 0x2c, 0x45, 0x44,
	0x4f, 0xd8, 0x02, 0x66, 0x61, 0x92, 0x50, 0xc2, 0xce, 0xc0, 0x11, 0x3f, 0x43, 0x9e, 0x97, 0x2a,
	0x94, 0x3b, 0x41, 0x5f, 0x30, 0x17, 0x20, 0xcb, 0x43, 0x95, 0x97, 0x3f, 0xe2, 0xfc, 0x8a, 0xce,
	0x6e, 0xe6, 0xe3, 0x3f, 0x7f, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xf4, 0x85, 0xb3, 0xf7,
	0x01, 0x00, 0x00,
}
