// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_edge.proto

package cds_cabinet_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EdgeGetRequest struct {
	Mode                 RetrieveMode `protobuf:"varint,1,opt,name=mode,proto3,enum=cds.cabinet.v1.RetrieveMode" json:"mode,omitempty"`
	Edge                 *Edge        `protobuf:"bytes,2,opt,name=edge,proto3" json:"edge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EdgeGetRequest) Reset()         { *m = EdgeGetRequest{} }
func (m *EdgeGetRequest) String() string { return proto.CompactTextString(m) }
func (*EdgeGetRequest) ProtoMessage()    {}
func (*EdgeGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec6de44fafa439a, []int{0}
}

func (m *EdgeGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EdgeGetRequest.Unmarshal(m, b)
}
func (m *EdgeGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EdgeGetRequest.Marshal(b, m, deterministic)
}
func (m *EdgeGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdgeGetRequest.Merge(m, src)
}
func (m *EdgeGetRequest) XXX_Size() int {
	return xxx_messageInfo_EdgeGetRequest.Size(m)
}
func (m *EdgeGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EdgeGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EdgeGetRequest proto.InternalMessageInfo

func (m *EdgeGetRequest) GetMode() RetrieveMode {
	if m != nil {
		return m.Mode
	}
	return RetrieveMode_ALL
}

func (m *EdgeGetRequest) GetEdge() *Edge {
	if m != nil {
		return m.Edge
	}
	return nil
}

type EdgeListRequest struct {
	Opt                  *ListOptions `protobuf:"bytes,1,opt,name=opt,proto3" json:"opt,omitempty"`
	Subject              string       `protobuf:"bytes,10,opt,name=subject,proto3" json:"subject,omitempty"`
	Predicate            string       `protobuf:"bytes,11,opt,name=predicate,proto3" json:"predicate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EdgeListRequest) Reset()         { *m = EdgeListRequest{} }
func (m *EdgeListRequest) String() string { return proto.CompactTextString(m) }
func (*EdgeListRequest) ProtoMessage()    {}
func (*EdgeListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec6de44fafa439a, []int{1}
}

func (m *EdgeListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EdgeListRequest.Unmarshal(m, b)
}
func (m *EdgeListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EdgeListRequest.Marshal(b, m, deterministic)
}
func (m *EdgeListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdgeListRequest.Merge(m, src)
}
func (m *EdgeListRequest) XXX_Size() int {
	return xxx_messageInfo_EdgeListRequest.Size(m)
}
func (m *EdgeListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EdgeListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EdgeListRequest proto.InternalMessageInfo

func (m *EdgeListRequest) GetOpt() *ListOptions {
	if m != nil {
		return m.Opt
	}
	return nil
}

func (m *EdgeListRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EdgeListRequest) GetPredicate() string {
	if m != nil {
		return m.Predicate
	}
	return ""
}

func init() {
	proto.RegisterType((*EdgeGetRequest)(nil), "cds.cabinet.v1.EdgeGetRequest")
	proto.RegisterType((*EdgeListRequest)(nil), "cds.cabinet.v1.EdgeListRequest")
}

func init() { proto.RegisterFile("service_edge.proto", fileDescriptor_5ec6de44fafa439a) }

var fileDescriptor_5ec6de44fafa439a = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x41, 0x4b, 0x03, 0x31,
	0x14, 0x84, 0x59, 0x2d, 0x4a, 0xdf, 0xca, 0x0a, 0xc1, 0x43, 0xa8, 0x3d, 0x2c, 0x3d, 0xed, 0xc5,
	0xa0, 0xeb, 0x6f, 0x10, 0x2f, 0x8a, 0x90, 0x3f, 0x20, 0xbb, 0xc9, 0x50, 0x23, 0xda, 0xc4, 0xe4,
	0x75, 0xf1, 0xe7, 0x4b, 0x22, 0x5a, 0xba, 0xc7, 0x79, 0xf3, 0xcd, 0x0c, 0x8f, 0x44, 0x42, 0x9c,
	0x9c, 0xc1, 0x2b, 0xec, 0x16, 0x2a, 0x44, 0xcf, 0x5e, 0x34, 0xc6, 0x26, 0x65, 0x86, 0xd1, 0xed,
	0xc0, 0x6a, 0xba, 0x5b, 0x5d, 0xa4, 0xb7, 0x21, 0xc2, 0xfe, 0xba, 0x2b, 0x3a, 0x90, 0x9b, 0x0f,
	0x6a, 0x1e, 0xec, 0x16, 0x8f, 0x60, 0x8d, 0xaf, 0x3d, 0x12, 0x8b, 0x5b, 0x5a, 0x7c, 0x7a, 0x0b,
	0x59, 0xb5, 0x55, 0xd7, 0xf4, 0x6b, 0x75, 0x5c, 0xa5, 0x34, 0x38, 0x3a, 0x4c, 0x78, 0xf6, 0x16,
	0xba, 0x90, 0xa2, 0xa3, 0x45, 0x6e, 0x94, 0x27, 0x6d, 0xd5, 0xd5, 0xfd, 0xd5, 0x3c, 0x91, 0xfb,
	0x75, 0x21, 0x36, 0xdf, 0x74, 0x99, 0xd5, 0x93, 0x4b, 0xff, 0x73, 0x37, 0x74, 0xea, 0x03, 0x97,
	0xb5, 0xba, 0xbf, 0x9e, 0x67, 0x33, 0xf9, 0x12, 0xd8, 0xf9, 0x5d, 0xd2, 0x99, 0x13, 0x92, 0xce,
	0xd3, 0x7e, 0x7c, 0x87, 0x61, 0x49, 0x6d, 0xd5, 0x2d, 0xf5, 0x9f, 0x14, 0x6b, 0x5a, 0x86, 0x08,
	0xeb, 0xcc, 0xc0, 0x90, 0x75, 0xf1, 0x0e, 0x87, 0xf1, 0xac, 0xbc, 0x7b, 0xff, 0x13, 0x00, 0x00,
	0xff, 0xff, 0x95, 0x27, 0xd9, 0xec, 0x2e, 0x01, 0x00, 0x00,
}
