// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_index.proto

package cds_cabinet_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IndexGetRequest struct {
	Index                *Index       `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Mode                 RetrieveMode `protobuf:"varint,2,opt,name=mode,proto3,enum=cds.cabinet.v1.RetrieveMode" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *IndexGetRequest) Reset()         { *m = IndexGetRequest{} }
func (m *IndexGetRequest) String() string { return proto.CompactTextString(m) }
func (*IndexGetRequest) ProtoMessage()    {}
func (*IndexGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46e40c52b04100e5, []int{0}
}

func (m *IndexGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexGetRequest.Unmarshal(m, b)
}
func (m *IndexGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexGetRequest.Marshal(b, m, deterministic)
}
func (m *IndexGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexGetRequest.Merge(m, src)
}
func (m *IndexGetRequest) XXX_Size() int {
	return xxx_messageInfo_IndexGetRequest.Size(m)
}
func (m *IndexGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexGetRequest proto.InternalMessageInfo

func (m *IndexGetRequest) GetIndex() *Index {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *IndexGetRequest) GetMode() RetrieveMode {
	if m != nil {
		return m.Mode
	}
	return RetrieveMode_ALL
}

type IndexListRequest struct {
	Opt                  *ListOptions `protobuf:"bytes,1,opt,name=opt,proto3" json:"opt,omitempty"`
	IndexId              string       `protobuf:"bytes,10,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	Value                string       `protobuf:"bytes,11,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *IndexListRequest) Reset()         { *m = IndexListRequest{} }
func (m *IndexListRequest) String() string { return proto.CompactTextString(m) }
func (*IndexListRequest) ProtoMessage()    {}
func (*IndexListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46e40c52b04100e5, []int{1}
}

func (m *IndexListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexListRequest.Unmarshal(m, b)
}
func (m *IndexListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexListRequest.Marshal(b, m, deterministic)
}
func (m *IndexListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexListRequest.Merge(m, src)
}
func (m *IndexListRequest) XXX_Size() int {
	return xxx_messageInfo_IndexListRequest.Size(m)
}
func (m *IndexListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexListRequest proto.InternalMessageInfo

func (m *IndexListRequest) GetOpt() *ListOptions {
	if m != nil {
		return m.Opt
	}
	return nil
}

func (m *IndexListRequest) GetIndexId() string {
	if m != nil {
		return m.IndexId
	}
	return ""
}

func (m *IndexListRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*IndexGetRequest)(nil), "cds.cabinet.v1.IndexGetRequest")
	proto.RegisterType((*IndexListRequest)(nil), "cds.cabinet.v1.IndexListRequest")
}

func init() { proto.RegisterFile("service_index.proto", fileDescriptor_46e40c52b04100e5) }

var fileDescriptor_46e40c52b04100e5 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xcf, 0x5d, 0x4a, 0xc5, 0x30,
	0x10, 0x05, 0x60, 0xa2, 0x5e, 0x7f, 0xa6, 0x72, 0x95, 0xa8, 0x10, 0xab, 0x0f, 0xa5, 0x4f, 0x05,
	0x31, 0x68, 0x5d, 0x84, 0x14, 0x14, 0x21, 0x1b, 0x28, 0x6d, 0x33, 0x60, 0x40, 0x9b, 0x98, 0xa4,
	0xc1, 0xe5, 0x4b, 0xa7, 0x22, 0xde, 0x3e, 0x9e, 0xe4, 0xe3, 0x1c, 0x06, 0x2e, 0x02, 0xfa, 0x64,
	0x06, 0x6c, 0xcd, 0xa8, 0xf1, 0x5b, 0x3a, 0x6f, 0xa3, 0xe5, 0xdb, 0x41, 0x07, 0x39, 0x74, 0xbd,
	0x19, 0x31, 0xca, 0xf4, 0x98, 0x9f, 0x86, 0xf7, 0xce, 0xa3, 0x5e, 0x7e, 0xf3, 0xec, 0x1f, 0x2d,
	0x1d, 0x9c, 0x35, 0x73, 0x7c, 0xc6, 0xa8, 0xf0, 0x6b, 0xc2, 0x10, 0xf9, 0x1d, 0x6c, 0x48, 0x08,
	0x56, 0xb0, 0x2a, 0xab, 0xaf, 0xe4, 0x6e, 0x9b, 0x24, 0xaf, 0x16, 0xc3, 0x1f, 0xe0, 0xe0, 0xd3,
	0x6a, 0x14, 0x7b, 0x05, 0xab, 0xb6, 0xf5, 0xed, 0xda, 0x2a, 0x8c, 0xde, 0x60, 0xc2, 0x57, 0xab,
	0x51, 0x91, 0x2c, 0x3d, 0x9c, 0x53, 0xc3, 0x8b, 0x09, 0x7f, 0x93, 0xf7, 0xb0, 0x6f, 0x5d, 0xfc,
	0x1d, 0xbc, 0x59, 0x97, 0xcc, 0xf2, 0xcd, 0x45, 0x63, 0xc7, 0xa0, 0x66, 0xc7, 0xaf, 0xe1, 0x98,
	0xd6, 0x5b, 0xa3, 0x05, 0x14, 0xac, 0x3a, 0x51, 0x47, 0x94, 0x1b, 0xcd, 0x2f, 0x61, 0x93, 0xba,
	0x8f, 0x09, 0x45, 0x46, 0xef, 0x4b, 0xe8, 0x0f, 0xe9, 0xd8, 0xa7, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xca, 0x90, 0xb3, 0x13, 0x2e, 0x01, 0x00, 0x00,
}
